### PR TITLE
Fix Bash prompt

### PR DESCRIPTION
**Pull request by gipert**
Extra `\e[m` was breaking it.

### CODE REVIEW

**Comment by oschulz** [comment]
Thanks!

**Comment by oschulz** [comment]
Now my prompt looks like this, though:

```
(cenvname)username@hostname:~$
```

@gipert can we have a space after the `(cenvname)` again?

**Comment by gipert** [comment]
uhm it should not look like this, see the PS1 value. are you overriding it somehow?

**Comment by oschulz** [comment]
Hm, indeed - I'll see what's going on there ...

**Pull request merged**
