### PR TITLE
Create windows version for cenv-ssh (cenv-ssh.bat)

### PR DESCRIPTION
**Pull request by patgo25**
Create windows version for cenv-ssh (cenv-ssh.bat)

### CODE REVIEW

**Comment by oschulz** [comment]
Thanks @patgo25 - does this work with VS-Code on Windows?

**Comment by patgo25** [comment]
Yes (at least on my Windows machine)

**Comment by oschulz** [comment]
Neat!

**Comment by gipert** [comment]
Is the required syntax here `host~cenv`? I think it's the other way round in the *nix script... but I like it more, `cenv~host` makes less sense to me

**Comment by oschulz** [comment]
It should be `cenv~host`, in `cenv~host.my.domain` would be something like a "virtual sub-host/domain" so it should be on the left.

**Comment by patgo25** [comment]
Ah yes in the batch script it's `host~cenv`. 
Replace lines 24&25 with
 ```
 set Cenv=%%a
 set Server=%%b
```
To get `cenv~host`

**Comment by oschulz** [comment]
Thanks, done.

**Pull request merged**
